spring.application.name=api-gateway-gymnasio
server.port=8088

# ==================== EUREKA ====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ==================== SECURITY (Keycloak JWT) ====================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gimnasio

# ==================== ACTUATOR ====================
management.endpoints.web.exposure.include=health,info,gateway

# ==================== SWAGGER / OPENAPI (Gateway) ====================
# Endpoint OpenAPI del propio gateway
springdoc.api-docs.path=/api-docs

# Swagger UI del gateway
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Mostrar en el Swagger UI los api-docs de los microservicios (a través del gateway)
springdoc.swagger-ui.urls[0].name=Miembros
springdoc.swagger-ui.urls[0].url=/miembros/api-docs
springdoc.swagger-ui.urls[1].name=Equipos
springdoc.swagger-ui.urls[1].url=/equipment/api-docs
springdoc.swagger-ui.urls[2].name=Clases
springdoc.swagger-ui.urls[2].url=/clases/api-docs
springdoc.swagger-ui.urls[3].name=Entrenadores
springdoc.swagger-ui.urls[3].url=/trainers/api-docs

# --- RUTA: MIEMBROS (8080) ---
spring.cloud.gateway.mvc.routes[0].id=miembros-service
spring.cloud.gateway.mvc.routes[0].uri=lb://miembros-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/miembros/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1

# --- RUTA: EQUIPOS (8081) ---
spring.cloud.gateway.mvc.routes[1].id=gym-equipment-service
spring.cloud.gateway.mvc.routes[1].uri=lb://gym-equipment-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/equipment/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1

# --- RUTA: CLASES (8082) ---
spring.cloud.gateway.mvc.routes[2].id=clases-service
spring.cloud.gateway.mvc.routes[2].uri=lb://clases-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/clases/**
spring.cloud.gateway.mvc.routes[2].filters[0]=StripPrefix=1

# --- RUTA: ENTRENADORES (8085) ---
spring.cloud.gateway.mvc.routes[3].id=trainer-service
spring.cloud.gateway.mvc.routes[3].uri=lb://trainer-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/trainers/**
spring.cloud.gateway.mvc.routes[3].filters[0]=StripPrefix=1

# ==================== AGGREGATION SERVICE URLs ====================
gateway.services.miembros=http://miembros-service
gateway.services.equipment=http://gym-equipment-service
gateway.services.clases=http://clases-service
gateway.services.trainers=http://trainer-service
